### ISSUE TITLE
Some advice with the .gitignore

### ISSUE THREAD

**Issue by andrew-w-ross** [Dawar/typescript-library-tutorial#1]
Excellent tutorial I've also been banging my head against how to do sub modules correctly. 
I think a little guidance on how to setup the .gitignore is needed for situations where you can't or don't want to check in compiled code.
Here is my `.gitignore` that I found worked :

```
#Don't just use * or the exclusions below won't work
/* 
# Add files you need to exclusions
!LICENSE
!README.md
!package.json
!tsconfig.json
!yarn.lock
# Add your directory
!src/
```

**Comment by Dawar** [comment]
This is great! Thanks for the contribution :) I've included it as a sample file that can be renamed to .gitignore to ignore the dist files in the sample library. I chose not to name it as .gitignore assuming most people creating Typescript-compiled libraries using this structure will be sharing them and want to commit dist files, but there's definitely scenarios that won't be the case as well. Appreciate you taking the time to share this!
